### PR TITLE
Fixed #75: add support for systems with plesk

### LINKED ISSUE #75: Failed CentOS 8.4 -> Almalinux with Plesk 18.0.35-2
Today i went to "upgrade" my machine with CentOS 8.4 to Almalinux with the script and failed.

Perhaps this is usefull to you to fix.

As this is a KVM Virtual Machine, i restored without problems. If you need some test feel free to ask.

```
cat /etc/redhat-release 
CentOS Linux release 8.4.2105
```

```
rpm -q psa
psa-18.0.35-2.centos.8+p18.0.35.2+t210526.1158.x86_64
```

```
[root@machine ~]# bash ./almalinux-deploy.sh 
Check root privileges                                                 OK
Check centos-8.x86_64 is supported                                    OK
Download RPM-GPG-KEY-AlmaLinux                                        OK
Import RPM-GPG-KEY-AlmaLinux to RPM DB                                OK
Download almalinux-release package                                    OK
Verify almalinux-release package                                      OK
Your OS is supported                                                  OK
Remove OS specific rpm packages                                       OK
Verifying...                          ########################################
Preparando...                         ########################################
Actualizando / instalando...
almalinux-release-8.4-2.el8           ########################################
Install almalinux-release package                                     OK
Remove centos-logos centos-logos-httpd packages                       OK
Install almalinux-logos almalinux-logos-httpd packages                OK
Backup of alternatives is done                                        OK
Última comprobación de caducidad de metadatos hecha hace 0:00:06, el mar 15 jun 2021 18:22:36 CEST.
Error: 
 Problema 1: package plesk-lmlib-0.2.4-1centos.8.210401.0902.x86_64 requires log4cplus >= 1.2.0.1, but none of the providers can be installed
  - log4cplus-1.2.0.1-1centos.8.210401.0902.x86_64 does not belong to a distupgrade repository
  - problem with installed package plesk-lmlib-0.2.4-1centos.8.210401.0902.x86_64
 Problema 2: package plesk-lmlib-0.2.4-1centos.8.210401.0902.x86_64 requires log4cplus >= 1.2.0.1, but none of the providers can be installed
  - cannot install both log4cplus-1.2.0-11.el8.x86_64 and log4cplus-1.2.0.1-1centos.8.210401.0902.x86_64
  - package sw-engine-3.35.0-1centos.8.210401.0902.x86_64 requires liblock_manager.so.2()(64bit), but none of the providers can be installed
  - package sw-engine-3.35.0-1centos.8.210401.0902.x86_64 requires plesk-lmlib >= 0.2.4, but none of the providers can be installed
  - cannot install the best update candidate for package log4cplus-1.2.0.1-1centos.8.210401.0902.x86_64
  - problem with installed package sw-engine-3.35.0-1centos.8.210401.0902.x86_64
(pruebe a añadir '--allowerasing' a la línea de comandos para reemplazar los paquetes que producen conflictos o '--skip-broken' para descartar los paquetes que no se pueden instalar o '--nobest' para no tener en cuenta sólo los mejores candidatos)
Run dnf distro-sync -y. Exit code: 1                                  ERROR
```

```
[root@machine ~]# dnf distro-sync -y
Última comprobación de caducidad de metadatos hecha hace 0:01:45, el mar 15 jun 2021 18:22:36 CEST.
Error: 
 Problema 1: package plesk-lmlib-0.2.4-1centos.8.210401.0902.x86_64 requires log4cplus >= 1.2.0.1, but none of the providers can be installed
  - log4cplus-1.2.0.1-1centos.8.210401.0902.x86_64 does not belong to a distupgrade repository
  - problem with installed package plesk-lmlib-0.2.4-1centos.8.210401.0902.x86_64
 Problema 2: package plesk-lmlib-0.2.4-1centos.8.210401.0902.x86_64 requires log4cplus >= 1.2.0.1, but none of the providers can be installed
  - cannot install both log4cplus-1.2.0-11.el8.x86_64 and log4cplus-1.2.0.1-1centos.8.210401.0902.x86_64
  - package sw-engine-3.35.0-1centos.8.210401.0902.x86_64 requires liblock_manager.so.2()(64bit), but none of the providers can be installed
  - package sw-engine-3.35.0-1centos.8.210401.0902.x86_64 requires plesk-lmlib >= 0.2.4, but none of the providers can be installed
  - cannot install the best update candidate for package log4cplus-1.2.0.1-1centos.8.210401.0902.x86_64
  - problem with installed package sw-engine-3.35.0-1centos.8.210401.0902.x86_64
(pruebe a añadir '--allowerasing' a la línea de comandos para reemplazar los paquetes que producen conflictos o '--skip-broken' para descartar los paquetes que no se pueden instalar o '--nobest' para no tener en cuenta sólo los mejores candidatos)

```

### PR DESCRIPTION
**Pull request by titan-dn**

### CODE REVIEW

File: almalinux-deploy.sh [hunk 1]
```diff
@@ -495,11 +495,21 @@ distro_sync() {
...
+        dnf_repos+=",PLESK_*-dist"
+    fi
+    dnf distro-sync -y "${dnf_repos}" || {
         ret_code=${?}
         report_step_error "${step}. Exit code: ${ret_code}"
         exit ${ret_code}
     }
+    # remove unnecessary repo
+    if [ "${panel_type}" == "plesk" ]; then
+        plesk installer --select-release-current --show-components
```
Comment (soksanichenko) [inline almalinux-deploy.sh:511]: This code will be unreachable if distro-sync failed

**Review by soksanichenko — CHANGES_REQUESTED** [review]

File: almalinux-deploy.sh (hunk 1 above)
Comment (titan-dn) [reply almalinux-deploy.sh:511]: Yes. And what?

**Review by soksanichenko — APPROVED** [review]

**Review by andrewlukoshko — APPROVED** [review]
